#!/bin/bash

spawn_pipe() {
    local pipe="$1"
    rm -rf "${pipe}"
    mkfifo "${pipe}"
    echo "--" >"${pipe}" &
}

# Load resources
xrdb -merge .Xresources
 
# Set the background color
xsetroot -solid black
 
WALLPAPER="${HOME}/Pictures/lisp.jpg"
if [ -f "${WALLPAPER}" ]; then
    xloadimage -onroot -zoom 150 -center -border black "${WALLPAPER}"
fi
xscreensaver -no-splash &
xfce4-power-manager &
redshift -l 55.751244:37.618423 -t 5700:3500 -b 1.0:0.8 &

spawn_pipe "/tmp/.layout"
spawn_pipe "/tmp/.volume"
